parameters:
  seed: 42
  source: "HG002.GRCh38.300x.bam"
  n_replicates: 10
  collapse: 0

  cpus_per_task: 2
  mem_mb: 16384
  runtime: 30

  tools:
    - gatk-constant-memory
    - gatk-high-accuracy
    - gatk-chained
    - samtools
    - sambamba
    - samsampleX

benchmarks:

# HLA-A
  templated-wgs-hla-a:
    region: "chr6:29941260-29945884"
    templates:
        - template-bams/HG01363.bam
        - template-bams/HG01941.bam
        - template-bams/HG02122.bam
        - template-bams/HG02127.bam
        - template-bams/HG02291.bam
        - template-bams/HG02678.bam
        - template-bams/HG03593.bam
        - template-bams/HG03780.bam
        - template-bams/HG03965.bam
        - template-bams/NA18547.bam


  uniform-wgs-hla-a:
    region: "chr6:29941260-29945884"
    target_depth: 30
    
# TP53
  templated-wegs-tp53:
    region: "chr17:7758460-7784220"
    templates:
      - template-bams/HG002-WEGS-8P5X-R1.bam

# CHR21
  uniform-wgs-chr21-30x:
    region: "chr21:1-46709982"
    target_depth: 30