benchmarks:
  wgs-uniform-30x:
    chr: "chr21"
    start: 1
    end: 46709982
    n_replicates: 10

    source: "HG002.GRCh38.300x.bam"
    coefficient: 0.1

    cpu: 2
    mem_mb: 16384
    time: "30:00"

  # wgs-uniform-5x:
  #   chr: "chr21"
  #   start: 1
  #   end: 46709982
  #   n_replicates: 10

  #   source: "HG002.GRCh38.300x.bam"
  #   coefficient: 0.0166667

  #   cpu: 2
  #   mem_mb: 16384
  #   time: "30:00"

  # wgs-chr21:
  #   chr: "chr21"
  #   start: 1
  #   end: 46709982
  #   n_replicates: 10

  #   collapse: 0
  #   templates:
  #       - HG01363.bam
  #       - HG01941.bam
  #       - HG02122.bam
  #       - HG02127.bam
  #       - HG02291.bam
  #       - HG02678.bam
  #       - HG03593.bam
  #       - HG03780.bam
  #       - HG03965.bam
  #       - NA18547.bam

  #   map_mode: "mean"
  #   sample_mode: "mean"
  #   source: "HG002.GRCh38.300x.bam"

  #   cpu: 2
  #   mem_mb: 16384
  #   time: "30:00"

  # wegs-8p5x-chr21:
  #   chr: "chr21"
  #   start: 1
  #   end: 46709982
  #   n_replicates: 10

  #   collapse: 0
  #   templates:
  #     - "HG002-WEGS-8P5X-GRCh38.bam"

  #   map_mode: "mean"
  #   sample_mode: "mean"
  #   source: "HG002.GRCh38.300x.bam"

  #   cpu: 2
  #   mem_mb: 16384
  #   time: "30:00"

  # wgs-brca1:
  #   chr: "chr17"
  #   start: 43044295
  #   end: 43170245
  #   n_replicates: 10

  #   collapse: 0
  #   templates:
  #     - HG01363.bam
  #     - HG01941.bam
  #     - HG02122.bam
  #     - HG02127.bam
  #     - HG02291.bam
  #     - HG02678.bam
  #     - HG03593.bam
  #     - HG03780.bam
  #     - HG03965.bam
  #     - NA18547.bam

  #   map_mode: "mean"
  #   sample_mode: "mean"
  #   source: "HG002.GRCh38.300x.bam"

  #   cpu: 2
  #   mem_mb: 16384
  #   time: "30:00"

  # wegs-8p5x-brca1:
  #   chr: "chr17"
  #   start: 43044295
  #   end: 43170245
  #   n_replicates: 10

  #   collapse: 0
  #   templates:
  #     - "HG002-WEGS-8P5X-GRCh38.bam"

  #   map_mode: "mean"
  #   sample_mode: "mean"
  #   source: "HG002.GRCh38.300x.bam"

  #   cpu: 2
  #   mem_mb: 16384
  #   time: "30:00"

  # wgs-tp53:
  #   chr: "chr17"
  #   start: 7661779
  #   end: 7687538
  #   n_replicates: 10

  #   collapse: 0
  #   templates:
  #     - HG01363.bam
  #     - HG01941.bam
  #     - HG02122.bam
  #     - HG02127.bam
  #     - HG02291.bam
  #     - HG02678.bam
  #     - HG03593.bam
  #     - HG03780.bam
  #     - HG03965.bam
  #     - NA18547.bam

  #   map_mode: "mean"
  #   sample_mode: "mean"
  #   source: "HG002.GRCh38.300x.bam"

  #   cpu: 2
  #   mem_mb: 16384
  #   time: "30:00"

  # wegs-8p5x-tp53:
  #   chr: "chr17"
  #   start: 7661779
  #   end: 7687538
  #   n_replicates: 10

  #   collapse: 0
  #   templates:
  #     - "HG002-WEGS-8P5X-GRCh38.bam"

  #   map_mode: "mean"
  #   sample_mode: "mean"
  #   source: "HG002.GRCh38.300x.bam"

  #   cpu: 2
  #   mem_mb: 16384
  #   time: "30:00"

  # wgs-hla-a:
  #   chr: "chr6"
  #   start: 29941260
  #   end: 29945884
  #   n_replicates: 10

  #   collapse: 0
  #   templates:
  #       - HG01363.bam
  #       - HG01941.bam
  #       - HG02122.bam
  #       - HG02127.bam
  #       - HG02291.bam
  #       - HG02678.bam
  #       - HG03593.bam
  #       - HG03780.bam
  #       - HG03965.bam
  #       - NA18547.bam
  #   map_mode: "mean"
  #   sample_mode: "mean"
  #   source: "HG002.GRCh38.300x.bam"

  #   cpu: 2
  #   mem_mb: 16384  
  #   time: "30:00"

  wegs-8p5x-hla-a:
    chr: "chr6"
    start: 29941260
    end: 29945884
    n_replicates: 10

    collapse: 0
    templates:
      - "HG002-WEGS-8P5X-GRCh38.bam"

    map_mode: "mean"
    sample_mode: "mean"
    source: "HG002.GRCh38.300x.bam"

    cpu: 2
    mem_mb: 16384
    time: "30:00"

  # wgs-brca1:
  #   chr: "chr17"
  #   start: 43044295
  #   end: 43170245
  #   n_replicates: 10

  #   collapse: 0
  #   templates:
  #     - HG01363.bam
  #     - HG01941.bam
  #     - HG02122.bam
  #     - HG02127.bam
  #     - HG02291.bam
  #     - HG02678.bam
  #     - HG03593.bam
  #     - HG03780.bam
  #     - HG03965.bam
  #     - NA18547.bam

  #   map_mode: "mean"
  #   sample_mode: "mean"
  #   source: "HG002.GRCh38.300x.bam"

  #   cpu: 2
  #   mem_mb: 16384
  #   time: "30:00"

  # wegs-8p5x-brca1:
  #   chr: "chr17"
  #   start: 43044295
  #   end: 43170245
  #   n_replicates: 10

  #   collapse: 0
  #   templates:
  #     - "HG002-WEGS-8P5X-GRCh38.bam"

  #   map_mode: "mean"
  #   sample_mode: "mean"
  #   source: "HG002.GRCh38.300x.bam"

  #   cpu: 2
  #   mem_mb: 16384
  #   time: "30:00"

  # wgs-tp53:
  #   chr: "chr17"
  #   start: 7661779
  #   end: 7687538
  #   n_replicates: 10

  #   collapse: 0
  #   templates:
  #     - HG01363.bam
  #     - HG01941.bam
  #     - HG02122.bam
  #     - HG02127.bam
  #     - HG02291.bam
  #     - HG02678.bam
  #     - HG03593.bam
  #     - HG03780.bam
  #     - HG03965.bam
  #     - NA18547.bam

  #   map_mode: "mean"
  #   sample_mode: "mean"
  #   source: "HG002.GRCh38.300x.bam"

  #   cpu: 2
  #   mem_mb: 16384
  #   time: "30:00"

  wegs-8p5x-tp53:
    chr: "chr17"
    start: 7661779
    end: 7687538
    n_replicates: 10

    collapse: 0
    templates:
      - "HG002-WEGS-8P5X-GRCh38.bam"

    map_mode: "mean"
    sample_mode: "mean"
    source: "HG002.GRCh38.300x.bam"

    cpu: 2
    mem_mb: 16384
    time: "30:00"

  # wgs-brca1-min:
  #   chr: "chr17"
  #   start: 43044295
  #   end: 43170245
  #   n_replicates: 10

  #   collapse: 0
  #   templates:
  #     - HG01363.bam
  #     - HG01941.bam
  #     - HG02122.bam
  #     - HG02127.bam
  #     - HG02291.bam
  #     - HG02678.bam
  #     - HG03593.bam
  #     - HG03780.bam
  #     - HG03965.bam
  #     - NA18547.bam

  #   map_mode: "mean"
  #   sample_mode: "min"
  #   source: "HG002.GRCh38.300x.bam"

  #   cpu: 2
  #   mem_mb: 16384
  #   time: "30:00"

  # wgs-brca1-mean:
  #   chr: "chr17"
  #   start: 43044295
  #   end: 43170245
  #   n_replicates: 10

  #   collapse: 0
  #   templates:
  #     - HG01363.bam
  #     - HG01941.bam
  #     - HG02122.bam
  #     - HG02127.bam
  #     - HG02291.bam
  #     - HG02678.bam
  #     - HG03593.bam
  #     - HG03780.bam
  #     - HG03965.bam
  #     - NA18547.bam

  #   map_mode: "mean"
  #   sample_mode: "mean"
  #   source: "HG002.GRCh38.300x.bam"

  #   cpu: 2
  #   mem_mb: 16384
  #   time: "30:00"

  # wgs-brca1-median:
  #   chr: "chr17"
  #   start: 43044295
  #   end: 43170245
  #   n_replicates: 10

  #   collapse: 0
  #   templates:
  #     - HG01363.bam
  #     - HG01941.bam
  #     - HG02122.bam
  #     - HG02127.bam
  #     - HG02291.bam
  #     - HG02678.bam
  #     - HG03593.bam
  #     - HG03780.bam
  #     - HG03965.bam
  #     - NA18547.bam

  #   map_mode: "mean"
  #   sample_mode: "median"
  #   source: "HG002.GRCh38.300x.bam"

  #   cpu: 2
  #   mem_mb: 16384
  #   time: "30:00"

  # wgs-brca1-max:
  #   chr: "chr17"
  #   start: 43044295
  #   end: 43170245
  #   n_replicates: 10

  #   collapse: 0
  #   templates:
  #     - HG01363.bam
  #     - HG01941.bam
  #     - HG02122.bam
  #     - HG02127.bam
  #     - HG02291.bam
  #     - HG02678.bam
  #     - HG03593.bam
  #     - HG03780.bam
  #     - HG03965.bam
  #     - NA18547.bam

  #   map_mode: "mean"
  #   sample_mode: "max"
  #   source: "HG002.GRCh38.300x.bam"

  #   cpu: 2
  #   mem_mb: 16384
  #   time: "30:00"